env = Environment()

env['APP_TARGET'] = 'ClientApp'
env['APP_SOURCES'] = ['ClientApp.cpp']
env['DEBUG'] = 0

env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')

