env = Environment()

env['APP_TARGET'] = 'ServerApp'
env['APP_SOURCES'] = ['ServerApp.cpp']
env['DEBUG'] = 0

env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')

