import os

Import('env')

_WEBSOCKETPP_INCLUDES = [Dir('../src').abspath]
_WEBSOCKETPP_SOURCES = ['WebSocketClient.cpp', 'WebSocketConnection.cpp',
	'WebSocketServer.cpp']
_WEBSOCKETPP_SOURCES = [File('../src/' + s).abspath for s in _WEBSOCKETPP_SOURCES]

_WEBSOCKETPP_LIBS = []
if env['PLATFORM'] == 'darwin':
	_WEBSOCKETPP_LIBS = ['libboost_random.a', 'libboost_regex.a']
	_WEBSOCKETPP_LIBS = [Dir('../lib/macosx/').abspath + '/' + s for s in _WEBSOCKETPP_LIBS]
else:
	# TODO
	pass

_WEBSOCKETPP_LIBS = [File(s) for s in _WEBSOCKETPP_LIBS]

env.Append(APP_SOURCES = _WEBSOCKETPP_SOURCES)
env.Append(CPPPATH = _WEBSOCKETPP_INCLUDES)
env.Append(LIBS = _WEBSOCKETPP_LIBS)

Return('env')
